name: Otobook
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.1
  google_mlkit_text_recognition: ^0.13.0
  retry: ^3.1.2
  shared_preferences: ^2.2.3
  image: ^4.2.0
  path_provider: ^2.1.4
  cunning_document_scanner: ^1.2.3
  csv: ^6.0.0
  google_mlkit_barcode_scanning: ^0.12.1
  camera: ^0.11.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/Splash_oto.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
ios: true
image:
  "assets/icon/icon.png"

 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo_oto.PNG
    - assets/Splash_Oto.svg
    - assets/pic1.svg
    - assets/icon.svg
    - assets/images/daffa.png
    - assets/images/dafiq.png
    - assets/images/damar.png
    - assets/images/nana.png
    - assets/images/pelangi.png
    - assets/about/about1.svg
    - assets/about/about2.svg
    - assets/icon/ai-icon.svg
    - assets/icon/ocr-icon.svg
    - assets/m.png
    - assets/p.png
    - assets/in.svg
    - assets/Car.svg
    - assets/icon/icon.png
    - assets/icon/Biru.svg
    - assets/icon/Kuning.svg
    - assets/placeholder.jpg
    - assets/profile_placeholder.jpg
    - assets/Splash_oto.png
    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  