// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5PfsaID7LBslKYKFW9ukeurymylC3jxA',
    appId: '1:856313868737:web:e421882eab0fe1ef9eff40',
    messagingSenderId: '856313868737',
    projectId: 'loginotobook-20859',
    authDomain: 'loginotobook-20859.firebaseapp.com',
    storageBucket: 'loginotobook-20859.appspot.com',
    measurementId: 'G-QTBXFM0YHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoqXQg9AqiU4FVWBS-2XCYE0loJaJFUNg',
    appId: '1:856313868737:android:0e8d471db34347409eff40',
    messagingSenderId: '856313868737',
    projectId: 'loginotobook-20859',
    storageBucket: 'loginotobook-20859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi0-LdePW1D36peUcNSi9fzhAFmFhfRpw',
    appId: '1:856313868737:ios:c278a6bbf908d13e9eff40',
    messagingSenderId: '856313868737',
    projectId: 'loginotobook-20859',
    storageBucket: 'loginotobook-20859.appspot.com',
    iosBundleId: 'com.example.otobook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi0-LdePW1D36peUcNSi9fzhAFmFhfRpw',
    appId: '1:856313868737:ios:c278a6bbf908d13e9eff40',
    messagingSenderId: '856313868737',
    projectId: 'loginotobook-20859',
    storageBucket: 'loginotobook-20859.appspot.com',
    iosBundleId: 'com.example.otobook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5PfsaID7LBslKYKFW9ukeurymylC3jxA',
    appId: '1:856313868737:web:1a379db4ed9c27109eff40',
    messagingSenderId: '856313868737',
    projectId: 'loginotobook-20859',
    authDomain: 'loginotobook-20859.firebaseapp.com',
    storageBucket: 'loginotobook-20859.appspot.com',
    measurementId: 'G-YHYEQXRRDC',
  );
}
